sudo: required
services:
  - docker
before_install:
- docker build -t deo-iuvante .
language: node_js
node_js:
- node
script:
- npm run lint
deploy:
  provider: script
  script: bash heroku_deploy
  on:
    branch: master
