sudo: required
services:
  - docker
language: node_js
node_js:
  - node
node_js:
  - "lts/*"
script:
  - bash heroku_deploy_test_stand
  - npm run lint
  - npm run build
  - npm run test:integration
deploy:
  provider: script
  script: bash heroku_deploy
  on:
    branch: master
