sudo: required
services:
  - docker
language: node_js
node_js:
- node
script:
- npm run lint
before_deploy:
- docker build -t deo-iuvante .
deploy:
  provider: script
  script: bash heroku_deploy
  on:
    branch: deployment
