#!/bin/bash
docker build -t deo-iuvante .
docker login -u=_ -p=$HEROKU_KEY registry.heroku.com
docker tag deo-iuvante registry.heroku.com/ikononov-deo-iuvante/web
docker push registry.heroku.com/ikononov-deo-iuvante/web
